# Generated by Django 6.0.2 on 2026-03-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'nav_order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='nav_order',
            field=models.PositiveIntegerField(default=0, help_text='Navbar mega menu order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Home page trending categories order'),
        ),
    ]
