# Generated by Django 6.0.2 on 2026-03-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_category_nav_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['nav_order', 'order'], 'verbose_name_plural': 'Categories'},
        ),
    ]
