# Generated by Django 6.0.2 on 2026-03-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('code', models.CharField(help_text='HEX code, e.g.,#ffff', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='style_group',
            field=models.CharField(blank=True, help_text="give me the same group name to same design products for identify the color variation (e.g., 'slim-fit-cotton-shirt-01')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
    ]
