# Generated by Django 6.0.2 on 2026-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_color_product_style_group_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_navbar',
            field=models.BooleanField(default=True, help_text='specific categories showing in navbar'),
        ),
    ]
