# Generated by Django 6.0.2 on 2026-03-17 18:03

import apps.products.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_image_alter_homebanners_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=600, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='categories/icons/'),
        ),
        migrations.AlterField(
            model_name='homebanners',
            name='image',
            field=models.ImageField(max_length=600, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(max_length=600, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=apps.products.models.get_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=600, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/gallery/'),
        ),
    ]
