# Generated by Django 6.0.2 on 2026-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_image_alter_homebanners_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_deals',
            field=models.BooleanField(default=False, help_text="It's is used to show budget deals in Home page"),
        ),
    ]
