# Generated by Django 6.0.2 on 2026-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_otp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email_otp',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
